### ISSUE TITLE
Issue in get message by last index

### ISSUE THREAD

**Issue by rakeshkatta1311** [twilio/twilio-chat-demo-android#79] opened 2018-12-07 13:34 UTC
For load earlier I am using getMessagesBefore function in which I have passed last message Id, count of the message and listner. I have got list of new messages,  but new messages contains a message whose id was passed in  getMessagesBefore function
For example, 

channel.getMessages().getMessagesBefore(1,30,listner);

where my last message id = 1.

Now in response I got the list of messages in which contain a message with id = 1 which is repeated.  

Is it normal behavior or I did something wrong?

Thanks,
Rakesh

**Comment by berkus** [comment] 2018-12-17 08:01
This looks extremely strange, I will need you to provide some logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). We are not able to reproduce this and we have tests covering such scenario.

**Comment by berkus** [comment] 2019-08-28 08:32
No logs reported, closing.

**Closed by berkus** 2019-08-28 08:32 UTC
Labels: category:no-logs
