### ISSUE TITLE
ChatClient shutdown() method crash

### ISSUE THREAD

**Issue by iTruff** [twilio/twilio-chat-demo-android#28] opened 2017-12-13 14:15 UTC
After calling ChatClient.shutdown(); in onDestroy() method of my activity i see this crash in logs:

```
12-13 16:13:56.414 com.brainagency.clevergig D/MainActivity: onDestroy: 
12-13 16:13:56.414 com.brainagency.clevergig D/TwilioClient: shutdown: 
12-13 16:13:56.414 com.brainagency.clevergig D/TwilioClient: shutdown: Start shutdown...
12-13 16:13:56.432 com.brainagency.clevergig W/TWC: TNRegNotificationCtxSession:       495654655216 | 12/13/16:13:56.432 | WARNING  | 18     | TNRegNotificationCtxSession | Could not operate with notification context in twilsock. Error 9
12-13 16:13:56.434 com.brainagency.clevergig E/TWC: TNWebsocket:       495618815216 | 12/13/16:13:56.434 | CRITICAL | 5      | TNWebsocket | Received error while waiting for message: Net Exception
12-13 16:13:56.436 com.brainagency.clevergig A/libc: invalid pthread_t 0x73650f54f0 passed to libc
12-13 16:13:56.437 com.brainagency.clevergig A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31626 (evergig - 31625), pid 31540 (gency.clevergig)
```

```
 @Override
    protected void onDestroy() {
        Log.d(TAG, "onDestroy: ");
        TwilioClient.getInstance().shutdown();
        Log.d(TAG, "onDestroy: After shutdown");
        super.onDestroy();
    }
```

```
 public void shutdown() {
        Log.d(TAG, "shutdown: ");

        if (mChatClient != null) {
            Log.d(TAG, "shutdown: Start shutdown...");
            mChatClient.shutdown();
            mChatClient = null;
            Log.d(TAG, "shutdown: Shutdown finished");
        }
    }
```

**Comment by berkus** [comment] 2017-12-13 14:35
And this is on Andoid 8.0 right?

**Comment by iTruff** [comment] 2017-12-13 14:39
Google Pixel, Android 8.1.0

**Comment by berkus** [comment] 2017-12-13 15:02
Interesting, I wonder why i cannot reproduce this. Could you share the code with me privately for debug purposes?

**Comment by iTruff** [comment] 2017-12-13 15:05
Sure, how can I do this?

**Comment by berkus** [comment] 2017-12-14 07:59
Do you have Telegram? Skype also works. Ping @berkus there.
You could also open a ticket on https://support.twilio.com and attach it there.

**Comment by iTruff** [comment] 2017-12-14 08:21
@berkus skype - icaesy

**Comment by berkus** [comment] 2017-12-14 08:42
Pinged you on skype.

**Comment by berkus** [comment] 2017-12-14 13:43
This seems to be a reproducible case for #19 and thanks @iTruff for providing reproduction code, I will close this one - keep an eye on #19 for when actual update goes out.

**Comment by kurtacious** [comment] 2018-06-12 15:13
Hi @berkus,

I'm experiencing a crash on `ChatClient#shutdown()` calls since upgrading the SDK from `2.0.8` to `3.1.0` in our app.  From what I've gathered, this only happens on devices with API 26 and above.

More specifically, I've experiences this crash on:
* Pixel 2XL (emulator), Android 8.0
* Pixel 2XL (emulator), Android 8.1
* Pixel XL, Android 9 developer preview 3

```
06-12 09:11:29.425  5866  5866 F libc    : invalid pthread_t 0x90108970 passed to libc
06-12 09:11:29.425  5866  5866 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5866 (xxx.xxxxxxxxxxx)
```

I have gathered a log per your instructions [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md) and will be happy to email them to you.

**Comment by berkus** [comment] 2018-06-12 18:03
@kurtacious thanks! Could you please open a zendesk ticket with support.twilio.com and post it's id here?

**Comment by kurtacious** [comment] 2018-06-12 18:42
@berkus I opened a ticket shortly after commenting here, but did not receive a ticket id.  Just a confirmation banner saying "Your request was successfully submitted."  However, I did hear back from support and they're escalating the issue (to you, I'm guessing 😄).

**Comment by berkus** [comment] 2018-06-12 18:50
Thanks, I will ping them tomorrow about it then.

**Comment by berkus** [comment] 2018-06-13 08:47
@kurtacious Thanks, I've received the logs. Just to confirm: are you calling shutdown while ChatClient is still receiving some channel messages?

**Comment by kurtacious** [comment] 2018-06-13 16:39
@berkus Can you clarify what you mean by receiving some channel messages?  I'm calling `shutdown()` on the chat client when my Activity is destroyed.  At that moment, there are not any outstanding requests to get channel messages (via `getLastMessages` or `getMessagesBefore`), but I do still have a listener attached to the channel.  Do you mind if I reach out to you on Skype?

**Comment by berkus** [comment] 2018-06-14 07:03
What i'm seeing in the logs is that chatclient just started booting up and it's immediately shut down - this causes some outstanding requests to fire into the void, causing a crash.

This is something that we do not plan to fix in the current iteration of SDKs, there's an update pending merge that should make things better as it uses a different async architecture internally. This means, we'd need to find a way to work around the issue on your side, for example by delaying chatclient shutdown until it is fully synced. To make sure this is doable we'd need to figure out use case for this instance.

Lets skype about it, add skype:berkus.

**Comment by berkus** [comment] 2018-06-19 11:35
With @kurtacious 's help I've reproduced one of the crashes.

**Comment by berkus** [comment] 2018-06-19 20:41
Release 3.1.1 should fix the related crashes (and some more).

Thank you all!

**Closed by berkus** 2018-06-19 20:41 UTC
Labels: filed-internally, fix:pending-release
