### ISSUE TITLE
Crash on old Android

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#67] opened 2018-10-09 05:22 UTC
### Description

Starting chat app crashes with linkage error.

### Steps to Reproduce

1. Starting my app (in general a mod of the demo app)

#### Expected Behavior

App starting and opening chat in background.

#### Actual Behavior

App crashes

```
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: find_library(linker.cpp:890): "/data/data/de.spieleck.app.badgers.debug/app_lib/libtwilio-rtd-native.so" failed to load previously
        at java.lang.Runtime.load(Runtime.java:340)
        at java.lang.System.load(System.java:521)
        at com.twilio.chat.internal.ReLinker.loadLibrary(sf:74)
        at com.twilio.chat.ChatClient.loadNativeLibraries(sf:187)
        at com.twilio.chat.ChatClient.<init>(sf:376)
        at com.twilio.chat.ChatClient.create(sf:287)

```

#### Reproduces how Often

100%

### Versions

All relevant version information for issue.

#### Chat Android SDK

4.0.0-rc12

#### Android API

Android 17, works on 28 (both real devices)

#### Android Device

S4 Active

**Comment by berkus** [comment] 2018-10-20 21:31
Hmm, thats bad. Ok, will test it on more devices.

**Comment by InI4** [comment] 2018-12-05 22:41
Did not go away with 4.0.0-rc15. The crash seems to have slightly changed (in timing), but this might also be other changes the App underwent in the last months:

```
12-05 23:39:14.469 de.spieleck.app.badgers.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:299)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
        at java.util.concurrent.FutureTask.run(FutureTask.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: find_library(linker.cpp:890): "/data/data/de.spieleck.app.badgers.debug/app_lib/libtwilio-rtd-native.so" failed to load previously
        at java.lang.Runtime.load(Runtime.java:340)
        at java.lang.System.load(System.java:521)
        at com.twilio.chat.internal.ReLinker.loadLibrary(sf:74)
        at com.twilio.chat.ChatClient.loadNativeLibraries(sf:187)
        at com.twilio.chat.ChatClient.<init>(sf:376)
        at com.twilio.chat.ChatClient.create(sf:287)
        at de.spieleck.app.badgers.chat.twilio.a.eu(sf:217)
        at de.spieleck.app.badgers.chat.twilio.a.b(sf:32)
        at de.spieleck.app.badgers.chat.twilio.a$4.run(sf:175)
        at de.spieleck.app.badgers.util.b$1.e(sf:29)
        at de.spieleck.app.badgers.util.b$1.doInBackground(sf:26)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:856) 
```

**Comment by InI4** [comment] 2018-12-07 07:40
OK, you mean this?
```

12-07 08:35:52.937 de.spieleck.app.badgers.debug E/dalvikvm: dlopen("/data/data/de.spieleck.app.badgers.debug/app_lib/libtwilio-rtd-native.so") failed: Cannot load library: find_library(linker.cpp:890): "/data/data/de.spieleck.app.badgers.debug/app_lib/libtwilio-rtd-native.so" failed to load previously
```

But file libtwilio-rtd-native.so exists, has 9MB and is strangely old, dated 10th of September 2018.

**Comment by InI4** [comment] 2018-12-07 07:45
Oops, deinstalled the app, reinstalled and now that lib files date changed to 12th of Juli 2018 and over 10MB.

**Comment by berkus** [comment] 2018-12-07 08:00
`failed to load previously`

find that previous instance.

**Comment by InI4** [comment] 2018-12-07 08:09
I am afraid, I do not understand, what previous instance of the lib? I mean I kind of did this, with the reinstallation I got to a seemingly older version. How/Where do I find previous versions of a lib? Downloading all your releases, unpacking und extracting the libs? And then how do I check that it is the one, that didn't load? Please advise?

**Comment by berkus** [comment] 2018-12-07 08:14
The previous instance of the load error.

The library is loaded when you first instantiate a ChatClient, since it now says "failed to load previously" it had already tried to load this library somewhere above, and that above part of the log will have the exact load error that happened.

**Comment by berkus** [comment] 2018-12-07 08:15
You could just post *whole log* from your unsuccessful run according to the [manual here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md).

**Comment by InI4** [comment] 2018-12-08 19:13
BTW, above problem persists with com.twilio:chat-android:4.0.0-rc18. (Might be obvious to you as you might have worked on different issues).

**Comment by InI4** [comment] 2018-12-10 12:48
Above problem persists with com.twilio:chat-android:4.0.0. (Might be obvious to you as you might have worked on different issues).

**Comment by berkus** [comment] 2018-12-10 12:49
Yes. Technically, we do not support any API below 19, but we're checking on an API 17 device anyway. Will post here when we have a result.

**Comment by InI4** [comment] 2018-12-10 22:17
OK, thx, technically it worked as well as elsewhere on API 17 till 3.1.1.

**Comment by berkus** [comment] 2018-12-11 10:38
We tested on various devices and on _some_ devices it does indeed work on API 17 and API 18 devices. The problem is this is not guaranteed.

**Comment by berkus** [comment] 2018-12-17 07:56
Closing, unsupported.

**Closed by berkus** 2018-12-17 07:56 UTC
Labels: category:bug, disposition:filed-internally, sdk-version:4.x, specific:android-version
