### ISSUE TITLE
Nested call back not getting result, want to get last message from each channel

### ISSUE THREAD

**Issue by DasJhaman** [twilio/twilio-chat-demo-android#159] opened 2021-02-10 17:37 UTC
### Description
- Wanted to get the last message of each channel, callbacks are not working in the loop, it's not getting triggered, loop getting executes but callbacks are not.

#### Code (optional)

Using the following code for getting last message:
```
private fun getLastMessage(channel: Channels, dataList: List<Data>) {
    dataList.forEachIndexed { index, any ->
        channel.getChannel(
                any.remoteChannelId,
                ChatCallbackListener<Channel>() {
                    it!!.messages?.getLastMessages(1, ChatCallbackListener<List<Message>>() {
                        if (it.size > 0) {
                            if (it.get(0).hasMedia()) {
                                any.lastMessage = "attachment"
                            } else {
                                Log.e("last friend", it.get(0).messageBody)
                                any.lastMessage = it.get(0).messageBody
                            }
                        }
                    })
                })
    }
}
```

#### Expected Behavior
Get Last message of each channel

#### Actual Behavior
Not getting any of message loop getting execute

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

```
// Log output when issue occurs
```

Or attach it as a file.

#### Logs

Yes, if you didn't collect the logs as described above, please collect the logs. Do not file the issue if you don't have enough information, this means having some logs, too.

#### Logs

Yes, seriously. Please send logs!

### Versions

All relevant version information for issue, fill in below:

#### Chat Android SDK

Which SDK version did you use? [eg. 2.0.8]

#### Android API

On which Android API version or versions does it happen? [eg. 18]

#### Android Device
Vivo

Device or devices on which the problem happens [eg. Nexus 5]

**Comment by berkus** [comment] 2021-02-10 17:52
I would suspect you have deliberately ignored ten lines asking to add logs?

**Comment by berkus** [comment] 2021-02-10 17:55
But anyway, here's the  problematic line:
```
ChatCallbackListener<Channel>() {
                    it!!.messages?.getLastMessages(1, ChatCallbackListener<List<Message>>() {
```

`messages` is null so it doesn't do anything. You should wait for complete channel synchronization first. [See docs](https://media.twiliocdn.com/sdk/android/chat/releases/6.2.0/docs/enumcom_1_1twilio_1_1chat_1_1Channel_1_1SynchronizationStatus.html).

**Comment by DasJhaman** [comment] 2021-02-10 17:57
How do I call channel synchronization, could you please share the documentation link.

**Comment by berkus** [comment] 2021-02-10 18:12
Something like [this](https://github.com/twilio/twilio-chat-demo-kotlin/blob/85dd764989c79f1fcb486512e0e03d036f1ca665/app/src/main/java/com/twilio/chat/app/common/extensions/TwilioExtensions.kt#L79-L100) and [this](https://github.com/twilio/twilio-chat-demo-kotlin/blob/85dd764989c79f1fcb486512e0e03d036f1ca665/app/src/main/java/com/twilio/chat/app/manager/MemberListManager.kt#L17-L18).

**Comment by DasJhaman** [comment] 2021-02-11 15:11
it.getUnconsumedMessagesCount(object : CallbackListener<Long>() {
                        override fun onSuccess(p0: Long?) {
                            if (p0 != null){
                                binding.tvUnReadMessagesCount.visibility = View.VISIBLE
                                binding.tvUnReadMessagesCount.text = ""+ p0

                            }
                        }

                    })

**Comment by DasJhaman** [comment] 2021-02-11 15:11
why unConsumed method not working as it giving me null.

**Comment by berkus** [comment] 2021-02-11 15:13
@DasJhaman because you did not mark any messages as read, so by default they are all unread.

**Comment by DasJhaman** [comment] 2021-02-11 15:15
I want to get the unread message count and want to display it on each chat room, which method is allowing so?

**Comment by DasJhaman** [comment] 2021-02-11 15:20
@berkus by default they are all unread than it should return me the count, or any other method to get an unread count?

**Comment by berkus** [comment] 2021-02-11 15:24
If it returns null you should query `Channel.getMessagesCount()`.

Not an  ideal usability but currently SDK is very explicit about the steps you need to do.

**Comment by DasJhaman** [comment] 2021-02-11 15:29
as per document `getMessageCount()` return me the total message count in that chat thread, but I need only unread message count, how can I get this.

**Comment by berkus** [comment] 2021-02-11 15:33
If all messages are unread, then you need the total message count - it equals unread message count (which equals ALL messages in the channel).

**Comment by DasJhaman** [comment] 2021-02-11 15:34
If suppose i don't have all messages unread, only 2 are unread then?

**Comment by berkus** [comment] 2021-02-11 15:39
Well, how many messages total do you have in the channel?

**Comment by DasJhaman** [comment] 2021-02-11 15:43
More than 50

**Comment by berkus** [comment] 2021-02-11 15:48
But getMessagesCount() returns only 2??

**Comment by DasJhaman** [comment] 2021-02-11 18:57
No it's returning me, total count.

**Comment by berkus** [comment] 2021-02-11 19:09
So it's correct, you have `total count` unread messages, what do you complain about?

If you had only 2 unread messages this would mean you marked some messages as read, but you didn't, so they are still unread. All as designed.

**Comment by Gray-Wind** [comment] 2021-02-11 19:14
You should mark at least one message as read with [this method](https://media.twiliocdn.com/sdk/android/chat/releases/6.2.0/docs/classcom_1_1twilio_1_1chat_1_1Messages.html#a7e820b5d1fd8495ea60ea8b66213ce83) and then `getUnconsumedMessagesCount` will return actual unread message count.

**Comment by berkus** [comment] 2021-02-11 19:18
By the way, its documented in detail in [this method description](https://media.twiliocdn.com/sdk/android/chat/releases/6.2.0/docs/classcom_1_1twilio_1_1chat_1_1Channel.html#aa38dbac393f68e4e2ae7de23e4f5ddb6), so make sure to read the documentation.

**Comment by DasJhaman** [comment] 2021-02-19 11:00
`    private fun getLastMessageDate(chatThreadsitems: MutableList<Data>) {
        chatThreadsitems.forEachIndexed { index, any ->
            Log.e("text","looping $ "+index)
            hayiChatClient.chatClient!!.channels!!.getChannel(
                any.remoteChannelId,
                ChatCallbackListener<Channel>() {
                    GlobalScope.launch {
                        it.waitForSynchronization()
                        any.channel = it
                        any.lastUpdatedAt = CommonMethods.getMileSeconds(it.lastMessageDate)
                    }

                })
        }

        ProgressDialogBox.dismissDialog()
        sortAndSetItems(chatThreadsitems)
    }`

@berkus @Gray-Wind some time my above method working fine and sometimes getting channel null, why this happening so, what is the best solution to deal with this. Thoug i am syncing the channel as well

**Comment by berkus** [comment] 2021-02-19 11:14
It could  be null because it's not found.  Callback listener has onError() method - is it called?

**Comment by DasJhaman** [comment] 2021-02-19 11:16
No, I am not using the onError method, I know it's null, why it's not found? Sometimes it's running perfectly some time making this issue? How can I execute this efficiency?

**Comment by berkus** [comment] 2021-02-19 11:21
What do the logs say when it's null?

**Comment by DasJhaman** [comment] 2021-02-19 11:27
E/text: looping $ 0
I/TWC:      | Chat IPM | client [api] get channels
D/TWC:      | SDK EntityCache | Returning Java object from cache
I/TWC:      | Chat IPM | channels: [api] get channel 446_447_uniqueName
D/TWC:      | Chat IPM | [BFGDg] got channel from cache 446_447_uniqueName
         | Chat IPM | channels: got from cache 446_447_uniqueName
E/text: looping $ 1
D/TWC:      | SDK EntityCache | Returning Java object from cache
I/TWC:      | Chat IPM | client [api] get channels
D/TWC:      | SDK EntityCache | Returning Java object from cache
I/TWC:      | Chat IPM | channels: [api] get channel 437_447_uniqueName
D/TWC:      | Chat IPM | [1G2Ro] got channel from cache 437_447_uniqueName

**Comment by DasJhaman** [comment] 2021-02-19 11:28
as per the loop, it's working perfectly but what is happening here my loop getting execute after that I am getting these logs.

**Comment by berkus** [comment] 2021-02-19 12:52
Can I see the logs please?

**Comment by DasJhaman** [comment] 2021-02-19 12:54
how can i share ?

**Comment by berkus** [comment] 2021-02-19 13:24
Proper trace level log should have at least 500 times more lines.

**Comment by berkus** [comment] 2021-02-19 13:27
You can enable detailed logging and submit the  resulting log file through help.twilio.com support (as it will contain  some details of your account as well).

**Comment by berkus** [comment] 2021-02-19 13:28
Here are [the details on enabling the log level](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md).

**Comment by DasJhaman** [comment] 2021-02-19 13:34
@berkus link of submit log redirecting me to here https://www.twilio.com/

**Comment by berkus** [comment] 2021-02-19 13:50
My bad, should be https://support.twilio.com/

**Comment by DasJhaman** [comment] 2021-03-01 19:16
Is there any way to set twilio connection time out,  if my wifi is off and i am going to connect twilio connection, webscoket is not calling onError method quickly, websocket holding the request more than 5 minutes. Is there any workaround?

**Comment by Gray-Wind** [comment] 2021-03-02 06:26
Yes, there is a way. You need to use [setCommandTimeout](https://media.twiliocdn.com/sdk/android/chat/releases/6.2.0/docs/classcom_1_1twilio_1_1chat_1_1ChatClient_1_1Properties_1_1Builder.html#a59859a8ef5515688ab8437340edfaa25) in options for a client creation.

**Comment by DasJhaman** [comment] 2021-03-04 08:24
Thanks, @Gray-Wind, can you guide me why I am getting channel status UNKNOWN for the invited user in channel descriptor, and not getting channel if i use getChannel method from remoteChannelSid. Please guide me on how to get the invited status of the channel.

**Comment by DasJhaman** [comment] 2021-03-04 09:29
Getting following error in log:
`D/TWC:      | Http HttpResponse.ctor | payload '{"code":54007,"status":403,"message":"Access forbidden for identity"}'
I/TWC:  172 | Sync TSCollectionOpenActivity | response status 403 body "{"code":54007,"status":403,"message":"Access forbidden for identity"}" (69 bytes)
W/TWC:  171 | Sync List | request 37 error code 54007: Access forbidden for identity
         | Chat IPM | [yGAiy] messages: error 54007 Access forbidden for identity`

**Comment by berkus** [comment] 2021-03-31 13:37
No logs, closing.

If you still have this problem,  please open  a  new ticket  with proper full log.

**Closed by berkus** 2021-03-31 13:37 UTC
