### ISSUE TITLE
onMemberDeleted Chat Android v2.0.8 Bug

### ISSUE THREAD

**Issue by danyhaddad** [twilio/twilio-chat-demo-android#37] opened 2018-03-22 14:32 UTC
Hello, 

I am using the chat android library of twilio and I faced a problem with v2.0.8 **onMemberDeleted**
It's never called .. I tried the version v2.0.7 and **onMemberDeleted** worked properly.
Can you please fix it.

Thank you.

**Comment by berkus** [comment] 2018-03-22 14:54
Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

Providing a sample of the code you use also helps.

In 2.0.8 the listener subscription logic has changed, are you sure you're not losing listeners from the Channel due to #26 for example?

**Comment by danyhaddad** [comment] 2018-03-22 15:33
No I'm not passing the Channel through a parcel.

below some code

` ChannelListener channelListener = new ChannelListener() {
            @Override
            public void onMessageAdded(Message message) {
                model.Message messageObj = new model.Message();
                messageObj.setText(message.getMessageBody());
                try {
                    JSONObject attributes = message.getAttributes();
                    messageObj.setDevice_os(attributes.optString("device_os"));
                } catch (JSONException e) {
                    e.printStackTrace();
                }
                String sourceId = message.getAuthor().split("_")[0];
                messageObj.setSourceDeviceId(sourceId);
                chatListener.onMessageReceived(messageObj);
            }

            @Override
            public void onMessageUpdated(Message message, Message.UpdateReason updateReason) {
                LogHelper.INSTANCE.write("onMessageUpdated");
            }

            @Override
            public void onMessageDeleted(Message message) {
                LogHelper.INSTANCE.write("onMessageDeleted");
            }

            @Override
            public void onMemberAdded(Member member) {
                LogHelper.INSTANCE.write("onMemberAdded");
            }

            @Override
            public void onMemberUpdated(Member member, Member.UpdateReason updateReason) {
                LogHelper.INSTANCE.write("onMemberUpdated");
            }

            @Override
            public void onMemberDeleted(Member member) {
                LogHelper.INSTANCE.write("onMemberDeleted");
                Intent onMemberDeletedIntent = new Intent(Constant.ON_MEMBER_DELETED_FILTER);
                context.sendBroadcast(onMemberDeletedIntent);
            }

            @Override
            public void onTypingStarted(Member member) {
                chatListener.onTypingStarted();
            }

            @Override
            public void onTypingEnded(Member member) {
                chatListener.onTypingEnded();
            }

            @Override
            public void onSynchronizationChanged(Channel channel) {
                LogHelper.INSTANCE.write("onSynchronizationChanged");
            }
        };
        chatChannel.getChannel().addListener(channelListener);`

**Comment by berkus** [comment] 2018-03-22 15:57
Can you please post some logs?

Open a ticket on support.twilio.com and refer to this issue - attach logs there.

You could also attach them here as a zip file.

**Comment by berkus** [comment] 2018-06-07 11:40
Hi, onMemberDeleted() has just been verified with Android 3.1.0 SDK and all works fine. Closing this, please reopen if you have further questions.

**Closed by berkus** 2018-06-07 11:40 UTC
Labels: sdk-version:2.x
