### ISSUE TITLE
Random issue when creating ChatClient

### ISSUE THREAD

**Issue by odinnou** [twilio/twilio-chat-demo-android#91] opened 2019-03-12 16:10 UTC
Hello, we love Twilio but we facing to a random issue when we setup the connection to the Programmable Chat Client with the Android SDK (**4.0.3**).

### once in four we got this error :

D/LoginActivity$onCreate: TWILIO - Client initialization : SUCCESS
D/LoginActivity$onCreate$1$onSuccess: onClientSynchronization STARTED
D/LoginActivity$onCreate$1$onSuccess: TWILIO - onConnectionStateChange CONNECTED
D/LoginActivity$onCreate$1$onSuccess: onClientSynchronization CHANNELS_COMPLETED
E/TWC: [2019-03-12 16:48:11.260] [rtd] [CRITICAL]        -1062524640 |      9 | Websocket | reportConnectFail read: SSLV3_ALERT_BAD_RECORD_MAC
D/LoginActivity$onCreate$1$onSuccess: TWILIO - onConnectionStateChange CONNECTING
W/TWC: [2019-03-12 16:48:11.340] [rtd] [WARNING]        -1051035360 |     19 | TSSubscriptions | Error while persisting subscriptions: establish
W/TWC: [2019-03-12 16:48:14.069] [rtd] [WARNING]        -1061480160 |      5 | Twilsock.Client | There is no pending request for such reply: RQ938473e7bdda42d08d4758ed2d5eba78. Skipping reply with code 401
W/TWC: [2019-03-12 16:48:14.179] [rtd] [WARNING]        -1049990880 |    511 | State.Initialising | Success reply can not be sent. Twilsock is not in connected state
E/TWC: [2019-03-12 16:48:14.179] [rtd] [CRITICAL]        -1049990880 |    512 | State.Connected | Server closed connection because couldn't authenticate: {"code":401,"status":"AUTHENTICATION_FAILED"}
E/TWC: [2019-03-12 16:48:24.157] [rtd] [CRITICAL]        -1058346720 |      9 | Websocket | reportConnectFail read: The WebSocket stream was gracefully closed at both endpoints

### And a multiple times (during 20s) we got these errors :

--

W/TWC: [2019-03-12 16:48:44.161] [rtd] [WARNING]        -1051035360 |    504 | SyncList | request 241 error code 1401: Unable to establish connection to Twilio Sync service
W/TWC: [2019-03-12 16:48:44.161] [rtd] [WARNING]        -1056257760 |    502 | SyncMap | request 240 error code 1401: Unable to establish connection to Twilio Sync service
W/TWC: [2019-03-12 16:48:44.161] [rtd] [WARNING]        -1053124320 |    506 | SyncList | request 242 error code 1401: Unable to establish connection to Twilio Sync service

--

D/LoginActivity$onCreate$1$onSuccess: onClientSynchronization COMPLETED
D/LoginActivity$onCreate$1$onSuccess: TWILIO - Client synchronized

**First question :** 
Is it a known issue ? For information, when we have this problem, we try to re-create the ChatClient and it works without ask a new JWT token, so we think that is not a JWT issue.

**Second :** 
Do you know a workaround ? 
The client does not trigger the errorListener, so we can't know when the client is on error.

**Third :** 
Is it possible to configure a timeout, to avoid waiting 20/25s before re-create the ChatClient ?

Here the implementation :

```
val builder = ChatClient.Properties.Builder()
val props = builder.createProperties()

ChatClient.setLogLevel(Log.WARN)
ChatClient.create(this, token, props, object : CallbackListener<ChatClient>() {
	override fun onSuccess(client: ChatClient?) {
		Timber.d("TWILIO - Client initialization : SUCCESS")
		client!!.setListener(object: ChatClientListener {
			override fun onChannelDeleted(p0: Channel?) {}
			override fun onInvitedToChannelNotification(p0: String?) {}
			override fun onClientSynchronization(synchronizationStatus: ChatClient.SynchronizationStatus?) {
				Timber.d("onClientSynchronization ${synchronizationStatus?.name}")
				if (synchronizationStatus == ChatClient.SynchronizationStatus.COMPLETED) {
					Timber.d("TWILIO - Client synchronized")
				}
			}
			override fun onNotificationSubscribed() { }
			override fun onUserSubscribed(p0: User?) {}
			override fun onChannelUpdated(p0: Channel?, p1: Channel.UpdateReason?) {}
			override fun onRemovedFromChannelNotification(p0: String?) { }
			override fun onNotificationFailed(p0: ErrorInfo?) {}
			override fun onTokenExpired() {}
			override fun onChannelJoined(p0: Channel?) {}
			override fun onChannelAdded(p0: Channel?) {}
			override fun onChannelSynchronizationChange(p0: Channel?) {}
			override fun onUserUnsubscribed(p0: User?) {}
			override fun onAddedToChannelNotification(p0: String?) {}
			override fun onChannelInvited(p0: Channel?) {}
			override fun onNewMessageNotification(p0: String?, p1: String?, p2: Long) {}
			override fun onConnectionStateChange(p0: ChatClient.ConnectionState?) {
				Timber.d("TWILIO - onConnectionStateChange ${p0?.name}")
			}
			override fun onError(p0: ErrorInfo?) {
				Timber.w("TWILIO - onError ${p0?.message} $p0")
			}
			override fun onUserUpdated(p0: User?, p1: User.UpdateReason?) {}
			override fun onTokenAboutToExpire() {}
		})
	}

	override fun onError(errorInfo: ErrorInfo?) {
		super.onError(errorInfo)
		Timber.e("TWILIO - Client initialization : ERROR. Cause : ${errorInfo.toString()}")
	}
})
```

Thanks in advance
Kind regards

Remi

**Comment by berkus** [comment] 2019-03-13 08:12
Hi Remi,

Thank you for your report.

This is an error we've seen reports about only recently and I personally believe this may be related to backend changes, please bear with us while we investigate the root cause. I will update here when we have more information.

**Comment by berkus** [comment] 2019-04-03 06:15
Remi, I believe I have a fix for this, it is being tested now.

**Comment by odinnou** [comment] 2019-04-05 08:23
Hello @berkus  do you have some news about it ?

Thanks in advance
Kind regards

**Comment by berkus** [comment] 2019-04-05 08:27
Hi @odinnou my plan is to release the fix early next week (mon-tue I suppose).

**Comment by odinnou** [comment] 2019-04-05 08:31
Thank you!

**Comment by droublon** [comment] 2019-04-09 11:38
Hi,

Same here.
We are currently working on a project using several hundred channels and this issue is critical for us.
We are forced to restart Twilio client several times to load our channels and it takes around 3 minutes to do it.

**Comment by berkus** [comment] 2019-04-09 12:10
Hi, the release version is `4.0.4-rc2` and you can try it now.

Please report if it fixes/improves things for you!

We are adding some more improvements before we release the final version, so if you could test this version and report about improvements it would be very helpful. The aim for final release is Wed-Thu this week.

**Comment by berkus** [comment] 2019-04-09 16:49
Could you please upload logs of the failure with `4.0.4-rc2`?

**Comment by berkus** [comment] 2019-04-11 11:49
@odinnou `4.0.4` is released, should fix your 1401 errors.

**Comment by ajitdubey-mob-ibtech** [comment] 2019-08-28 07:18
@berkus I am facing the same. Can you please suggest workaround of it. 

Error:

>ChatClientManager: Chat sdk Login Error------------------------------

 >ChatClient(native) | Failed to create the ChatClient: FAILURE 1401 Unable to establish connection to Twilio Sync service

Thanks

**Comment by berkus** [comment] 2019-08-28 08:29
@ajitdubey-mob-ibtech which version of SDK are you using?

**Comment by ajitdubey-mob-ibtech** [comment] 2019-08-29 06:00
@Berkus 4.2.0 but as of now revert back to 4.0.0.
In 4.0.0 is working fine.

**Comment by berkus** [comment] 2019-08-29 07:47
@ajitdubey-mob-ibtech could you please provide a log from 4.2.0 when this happens? It really shouldn't.

**Comment by berkus** [comment] 2020-01-27 07:28
Closing as no response.

**Closed by berkus** 2020-01-27 07:28 UTC
