### ISSUE TITLE
Version 2.0.2 Channel callback bug

### ISSUE THREAD

**Issue by iTruff** [twilio/twilio-chat-demo-android#26] opened 2017-12-07 11:53 UTC
Hi there. I'm using Programmable Chat Android SDK for chat in my application. Today i saw that there is a new version of SDK version 2.0.2 (i was using 2.0.1). After updating version of the Twilio SDK, compiling my app and testing it for few minutes i noticed that no any messages appears in my chat list. After small research i understand that the problem is in ChannelListener. After adding few channel listeners to one channel, callbacks like onMessageAdded, onMessageDeleted only called in first added listener. I read all release notes and didn't found any changes connected with my problem. 

Any comments?

**Comment by berkus** [comment] 2017-12-07 12:05
In 2.0.2 the channel listener handling has changed. Can you describe fully reproducible scenario so i can look into it?

It's important when these listeners go in and out of scope, because now they are attached to the actual Channel object and if it is released - the listeners will be gone.

**Comment by iTruff** [comment] 2017-12-07 12:19
1. In one fragment (ChannelListFragment) i create ChatClient and retrieve all channels.
2. Then i add ChannelListener to all channels.
3. After clicking on some channel, i put this channel object to Bundle and start new activity.
4. In onCreate() method of opened activity i am getting this channel and add one more ChannelListener.
5. Now, after sending messages from web or another phone to this user, only ChannelListener added in first step works.

**Comment by berkus** [comment] 2017-12-07 12:25
The way it currently implemented, passing Channel through a Parcel will lose all handlers, sorry about that.

I'll look into improving this.

**Comment by iTruff** [comment] 2017-12-07 12:27
Sad to hear, but thanks for help.

**Comment by berkus** [comment] 2020-10-26 11:26
Hi!

For newest Conversations SDK we dropped support for Parcelable from the Channel so it should be now clear that it is not safe to put it through Parcel. Instead, pass channel SID and reconstruct the Channel on the other side by calling `client.getChannelBySid(sid)`. This is safe and should work fine.

**Closed by berkus** 2020-10-26 11:26 UTC
Labels: category:enhancement, sdk-version:2.x, sdk-version:obsolete
